name: learn-github-actions #name workflow
on: [push]
jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.3.1
  check-bats-version: #name job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: python -V
  
