name: learn-github-actions #name workflow
on: [push]
jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.3.1
      - run: python -V
  check-bats-version: #name job
    runs-on: ubuntu-latest
    steps:
      - run: ls -a
      - uses: actions/checkout@v2 
      - run: ls -a
      - run: python -V
  
  ssh-remote-server:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_ED25519 }}
        port: ${{ secrets.PORT }}
        script: ls -a
  
